### ISSUE TITLE
Migrate the documentation to `gitpod-io/gitpod`

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1393]
Due to a technical limitation with SvelteKit (it didn't support symlinks for routes) at the time we initially developed this website (early April 2021), we migrated the docs from `gitpod-io/gitpod` into the `gitpod-io/website` repo.

The technical limitation no longer exists and it's time to migrate the documentation back in the `gitpod-io/gitpod` main repository. It is important to understand that we only migrate Markdown files. If a Markdown file requires Svelte components, such as the Quickstarts page, these Svelte components continue to live in the `gitpod-io/website` repo.

An initial test was done in #1367.

**Tasks**
- [x] Migrate the following into `src/lib` so we can use `$lib` to import files (#1394)
  - [x] `src/components`
  - [x] `src/contents`
  - [x] `src/stores`
  - [x] `src/types` (re-think this generally, this should be `*.d.ts` files instead
- [x] Move `src/routes/docs` to `$projectRoot/gitpod/docs` and symlink `src/routes/docs` -> `../../gitpod/docs` (#1398)
- [x] Evaluate a dynamic approach to generate the docs menu based on the directory structure within `$projectRoot/gitpod/docs` (#1401)
- [ ] Move all `$projectRoot/gitpod/docs` files to the `docs` directory in `gitpod-io/gitpod`
- [ ] Replace `$projectRoot/gitpod` with the `gitpod-io/gitpod` submodule
- [ ] Write a GitHub action that runs periodically to update the submodule & redeploy the website
  * ❓ Do we want to make this more explicit and require a pull request in the `gitpod-io/website` repo?
