### ISSUE TITLE
Automatically generate the left-side docs menu

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1401]
For `/docs/*` URLs, we display a menu on the left-hand side that is currently hard-coded in `src/lib/contents/docs/menu.ts`.

In #1393, we move the documentation to a different repository and updating the `menu.ts` file in the website repo is no longer a convenient workflow. We need to auto-generate the menu based on frontmatter available in the documentation Markdown files.

**Tasks**
- [ ] Remove all unused frontmatter properties in `gitpod/docs/**/*.md`.
- [ ] Add a new `status` frontmatter property to mark menu items as "Beta" or "Soon" (possibly others in the future). See https://www.gitpod.io/docs/editors for how it will be used
- [x] Write a new `handle*` function in `src/hooks.ts` to parse the documentation frontmatter and generate the menu.
- [x] Update the `getSession()` function in `src/hooks.ts` to expose the generated docs menu.
- [ ] Update `gitpod/docs/__layout.svelte` to use the generated docs menu.
  - [ ] Test on mobile
  - [ ] Test on desktop
- [ ] Remove `src/lib/contents/docs/menu`

**Comment by mikenikles** [comment]
@Cahllagerfeld is this issue still valid?

**Comment by Cahllagerfeld** [comment]
It is in regards for versioning, I can link that issue to the relevant PR 👍

**Comment by mikenikles** [comment]
👍 One for tomorrow's daily sync :)

**Comment by Cahllagerfeld** [comment]
That's not relevant anymore, closing it
