### ISSUE TITLE
Website Performance & SEO: Image Optimisation

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1463]
**Issue:**
we need to optimize our images to improve relevance and performance in regular search and image search.

- The image files should be provided in a compressed and web-optimised form with a suitable file name.
- The images should be resized correctly during the page load.
- It is recommended to provide a separate image sitemap for search engines.

**To Do's**

- [x] add dimensions to these images: https://docs.google.com/spreadsheets/d/1Nmy_BJ5hh2zm4aR4PemHHPEOE_UqFHkzwY3XOhxGsmE/edit#gid=0

- [x] adjust images sizes: https://docs.google.com/spreadsheets/d/1uY14BtHObojO2STmP4A0K13QwhHDqsSkXICjDdZ39HI/edit#gid=0

- [x] efficiently encoded images: https://docs.google.com/spreadsheets/d/17EYHhZJwKiMOBihnArxXfMkAXybqgu83w0PmE8mRVoI/edit#gid=0

- [x] Serve images in next gen formats: https://docs.google.com/spreadsheets/d/1r_gS-aEv7o0bcVCMTUrg8OFvGyNHKU4H9snUACwg6nw/edit#gid=0 see also [Image Analysis Results](https://webspeedtest.cloudinary.com/results/220113_AiDcZB_4388893496a7bfff075029f8efa94331)

- [ ] suitable file names
- [ ] provide a separate image sitemap for search engines

Related issue:
https://github.com/gitpod-io/website/issues/155

**Comment by Siddhant-K-code** [comment]
![image](https://user-images.githubusercontent.com/55068936/193532636-d262b6f9-9803-42ee-a95e-c5c4354c24c0.png)

**Comment by Siddhant-K-code** [comment]
This issue is kind of an `Epic` that has a lot of issues internally. Will address them on this PR (would take a longer time then usual)

**Comment by Siddhant-K-code** [comment]
This is On Hold. Because it will create merge conflicts due to #2725 

[Internal discussion](https://gitpod.slack.com/archives/C01KGM9ETU6/p1666149503412759)

cc: @chrifro @Cahllagerfeld

**Comment by chrifro** [comment]
What's the status of this issue now that #2725 will be discontinued and no longer effects this issue  @Siddhant-K-code ?

**Comment by Siddhant-K-code** [comment]
We were waiting for #2725, Now Since it is resolved now. I Will take this up in the following week. 🙏🏼

**Comment by Siddhant-K-code** [comment]
> provide a separate image sitemap for search engines

Doesn't seem to be a required thing, As far as i read on internet. Will discuss this later, if we feel like having this. 

Rest, all issues are resolved now ✨. Closing this **Epic** 🚀
