### ISSUE TITLE
Automate the `/changelog` content

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1482]
In my 1:1 today with Johannes, we agreed to:
* [x] Include all `gitpod-io/gitpod` PRs which have their "Release Notes" section completed in the `/changelog` "Fixes & Improvements" section.
* [x] Add avatars to each PR instead of summarized at the bottom
* [x] Remove the teams headings introduced in the [January 14, 2022 changelog](https://www.gitpod.io/changelog/dotfiles-support-in-beta#fixes-and-improvements).

**Tasks**
* [x] Create a script that uses the GitHub GraphQL API to generate the "Fixes & Improvements" section. The script:
  * [x] Uses the `CHANGELOG_GITHUB_ACCESS_TOKEN` environment variable as the GitHub API authentication token. If the env variable is not set, print a message and exit. Do not store or log this token.
  * [x] Accepts positional `release-date`, `from` and `to` arguments
  * [x] Fetches all `gitpod-io/gitpod` PRs merged between `from` and `to`
  * [x] Discards PRs that have no "Release Notes" section. Accepts PRs with a code block in their "Release Notes" section.
  * [x] Creates a `src/lib/contents/changelog/[from].md` file based on a template and inserts the following for each PR:
    * `- [#xyz](https://github.com/gitpod-io/gitpod/pull/xyz) - [Release Notes content from the PR] <Contributors usernames="username1,username2" />`
* [x] Update the Changelog page in Notion with the new release process

See the [engineering team's scripts](https://github.com/gitpod-io/gitpod/tree/main/dev/changelog) for potential ideas.
