### ISSUE TITLE
SEO: update meta titles and descriptions based on keyword targeting concept

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1546]
**Problem**
Many meta titles are out-of-date, were randomly created, too short or/and don't include our keywords.

**Solution**
We created a [keyword targeting concept](https://www.notion.so/gitpod/Keyword-targeting-concept-d985ef8047864b4e829329a60a85c7c1) to identify the most relevant keywords based on search intent and Gitpod's benefit.

**Next steps**
- [x] update the meta titles of the most relevant pages
- [x] update the meta description
- [x] minor additional changes to some websites to fit the keyword targeting
- [ ] make sure /community is indexed. currently, it highlights community.gitpod.io instead
- [ ] add a meaningful meta description to gitpod.io/workspaces

Note: all required changes are marked in blue in the table [here](https://www.notion.so/gitpod/Keyword-targeting-concept-d985ef8047864b4e829329a60a85c7c1)

**Comment by Cahllagerfeld** [comment]
<img width="325" alt="grafik" src="https://user-images.githubusercontent.com/43843195/154034858-1db91781-ee5d-4e79-97e3-2d5ab049984e.png">
There are currently quite a few backlings to `community.gitpod.io`. When linking them to `gitpod.io/community` we might not have an adaquate link anymore, because some of the current links are pointing to specific threats. What shall we do with these?

**Comment by Cahllagerfeld** [comment]
I think the tags for `/workspaces` need to be addressed by the WebApp-Team, right? @mikenikles

**Comment by Cahllagerfeld** [comment]
We need to find a solution for the current backlings to the discourse forum. An Idea @mikenikles came up with is adding corresponding docs for the linked threats and link them. With this we are able to get rid of the current backlinks to the old forum.

**Comment by ChristinFrohne** [comment]
>I think the tags for /workspaces need to be addressed by the WebApp-Team, right?
Yes, makes sense. Have you opened an issue for that for the WebApp team or fixed it yourself? I'd like to make sure that no action slips through the cracks. Let me know if I can support @Cahllagerfeld
