### ISSUE TITLE
SEO: optimize meta tags

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1592]
Note: this should be addressed after gitpod-io/website#1546 and gitpod-io/gitpod#8196 are fixed to avoid duplicate work

**To do's:**

- [ ] meta titles are too short (ca. 60 characters). Many titles are already fixed by gitpod-io/website#1546, gitpod-io/gitpod#8196 and gitpod-io/website#1469 the remaining titles that are too short can be fixed e.g. by adding "- Gitpod", the first sentence of the page "About Gitpod - Open source developer platform", "Integrations for GitLab, GitHub and Bitbucket projects" or a short explanation e.g. "Privacy Policy - your data is safe with us". [List of affected pages](https://docs.google.com/spreadsheets/d/15h4ZBNXNer_emqlOcIYvADvIKozX8x2cwGCcLaZwMzg/edit#gid=0)

- [ ]  meta descriptions too short. Can be fixed e.g by adding the first sentence of the page to the description support - "Need help? Did you face a bug or do you have a support request? Please get in contact and we’ll get onto it right away." [List of affected pages](https://docs.google.com/spreadsheets/d/1gCeG7vDIfj4CIgs4b80jeSJcsuHhGjjBNCttcWUm4vI/edit#gid=0)

<s> 
- [ ] make sure there are no URLs with duplicate meta descriptions (lower priority) [affected pages](https://docs.google.com/spreadsheets/d/1eqiy3_HQvJjp2bmgz_CkNm2D93omSwZWVV6UyAXE86U/edit#gid=0)

- [ ] meta title tag is not too long (around 60 characters).(lower priority) [affected pages](https://docs.google.com/spreadsheets/d/1cOUky0tyk0GA-AV2dJobXe5azKDFlwTu6yOTbTWMWW8/edit#gid=0)  </s>

- [x] meta descriptions are not too long - max 160 characters (lower priority) [affected pages](https://docs.google.com/spreadsheets/d/1Ns9Jfrpw3txDOR5zAA2VgtLAxj_iRu8v2QKtw-I8Aso/edit#gid=0)
**Note:**
keep in mind to add a proper meta title & description for all new pages

**Comment by nisarhassan12** [comment]
> Note: this should be addressed after https://github.com/gitpod-io/website/issues/1546 and https://github.com/gitpod-io/gitpod/issues/8196 are fixed to avoid duplicate work
@ChristinFrohne #1546 is merged. Should I start working on it? as we are not sure when [8196](https://github.com/gitpod-io/gitpod/issues/8196) is gonna be worked upon. Thanks

**Comment by ChristinFrohne** [comment]
I moved #8196 to the WebApp inbox. But you can already start working on this issue now. Just ignore the affected page with a workspace URL. You also need to watch out for recent fixes as many meta tags have already been optimized in other PRs. For the first two issues, the list of affected pages is very long although many of them are already resolved. Still, you don't need to adjust all of them. Let's focus on the most relevant pages


Many affected pages are gitpod.io/docs/languages/xyz. As the documentation has been moved, it probably makes sense to deindex these pages. WDYT @mikenikles ?

Thanks for looking into this @nisarhassan12 ! 🙏

**Comment by nisarhassan12** [comment]
Thanks, @ChristinFrohne sounds good.

**Comment by nisarhassan12** [comment]
- [ ] Regarding meta descriptions being short we have the exact same meta description across various all the Docs pages 

@mikenikles  Should we address this as well i.e having different meta descriptions for all the individual pages? Also the current meta description for all the pages is `Explore the documentation to learn more about Gitpod.io and Gitpod Self-Hosted.` can you suggest a new bigger description. Thanks

**Comment by nisarhassan12** [comment]
> - [x] meta descriptions are not too long - max 160 characters (lower priority)

the items listed in the doc for this todo are fixed in https://github.com/gitpod-io/website/pull/1774/commits/bb91d21966e6703c1b8b89a456c4d2ffea20e1a3 we didn't need to fix the ones for the changelog as they are already de-indexed from from search engines.

**Comment by nisarhassan12** [comment]
@chrifro when you get time. Please review https://github.com/gitpod-io/website/pull/1774 which fixes small parts of it.
