### ISSUE TITLE
Guides - Post-Launch checklist

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#1740]
From [this comment](https://github.com/gitpod-io/website/issues/709#issuecomment-891650587):
- [ ] create GitHub issue template
- [ ] review existing guides and contact authors if they would like to publish it (see [this comment](https://github.com/gitpod-io/website/issues/709#issuecomment-875401188) for links)
- [ ] communicate the possibility to submit guides on Twitter
- [ ] Add content from #740 as a new guide
