### ISSUE TITLE
Make Sveltekit-App Platform agnostic

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/website#1746]
Due to several outages at Netlify we want to make the App Platform Agnostic, so it runs on Vercel & Netlify (maybe Cloudflare in the future as well).

Steps to get this done: 

- [x] Write [RFC](https://www.notion.so/gitpod/Make-Marketing-Website-Platform-agnostic-ca9699da8c6c4a13ab7e8f8e8e7ed2f8)
- [x] Generate Redirects File for both Platforms => #1752 
- [x] Convert Endpoints from Netlify-Functions to Sveltekit-Endpoints => #1754 #1755 #1757 
- [ ] Setup Vercel for Website Repo
- [ ] Configure DNS properly
- [ ] Enforce Node.js 14 in the `package.json` and ensure we use it in Gitpod workspaces => #1758 
- [x] Introduce ADR => #1763 
- [x] Remove Netlify relicts with cleanup-commit => #1762 
- [ ] Monitor Vercel status in Gitpod's overall observability tools

**Comment by Cahllagerfeld** [comment]
Current Discussion: 
- Will there be SEO-Issues if we have two deployed versions of your website? There will be two domains out there that serve exactly the same content. We need to check if its possible to `noindex` the one that isn't in production currently.
- Vercel (unfortunately) doesn't support `Node v16`. This means we need a custom Dockerfile that prepares that environemnt for us. (#1758). This results in a slower startup-performance for the workspace. A possible solution would be to build the required Dockerimage and push it to a registry from where Gitpod can pull it. By doing so we can save the actual build step on workspace-start.
