### ISSUE TITLE
Update /about

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3111]
Make sure /about is up to date. 

**Required changes**

- [x] add [this Redmonk article](https://redmonk.com/jgovernor/2022/12/01/the-year-of-the-cloud-development-environment/) to the news section (you can find the logo [here](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=6032%3A10043&t=1si1RcgwrmhLo7FQ-1)) -- #3133
- [x] update investor section (messaging needed by @MichaelAring ) -- #3136
- [x] swap "two CEOs are better than one" blog post with https://www.gitpod.io/blog/future-of-software-cdes (should be the first one in the list) -- #3133
