### ISSUE TITLE
homepage sprint (part 1): update quotes 

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3371]
First round of updates to the homepage. More tasks will follow soon, but I think it makes sense to split them up and to already get started until the other changes are finalised. 
 cc @Siddhant-K-code 

**Tasks:**

- [x] remove "start from any Git context" sections
<img width="235" alt="Bildschirm­foto 2023-02-03 um 08 41 45" src="https://user-images.githubusercontent.com/46345125/216541145-d3e67cb0-8cf5-4646-97c1-fc107721610f.png">

- [x] remove contact widget
<img width="254" alt="Bildschirm­foto 2023-02-03 um 08 41 52" src="https://user-images.githubusercontent.com/46345125/216541195-f96cde54-9795-4c40-b63c-f93dc43d1f98.png">

- [ ] change CTA from "get a demo" to "contact sales"
<img width="182" alt="Bildschirm­foto 2023-02-03 um 08 43 46" src="https://user-images.githubusercontent.com/46345125/216541368-03f5552a-e359-4928-8d74-491994b24d1b.png">

- [ ] update quotes section. See new quotes [here](https://www.notion.so/gitpod/Quote-carousel-for-homepage-8294e398d35d419c9f4f75eb98e2dae5)

**Comment by Siddhant-K-code** [comment]
> remove contact widget

from homepage or from whole website?
