### ISSUE TITLE
Polish "get started" section

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3381]
**Tasks**

- [x] align button height to 48px for both "continue with XYZ" and the workspace examples
- [ ] update logos for the example workspaces -> color and sizes (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=8898%3A17416&t=hnSPrZItohUwUOAC-1))
- [x] increase spacing in front of the example workspace logos to align with the mockup

|status quo| mockup|
|-|-|
|<img width="492" alt="Bildschirm­foto 2023-02-06 um 11 19 06" src="https://user-images.githubusercontent.com/46345125/216946469-a036d853-d5af-4079-b01d-1cb2431cc457.png">|<img width="480" alt="Bildschirm­foto 2023-02-06 um 11 19 10" src="https://user-images.githubusercontent.com/46345125/216946485-f4b56fef-6690-4f28-8791-585edf252f92.png">

**Comment by ShashwatNautiyal** [comment]
@chrifro You can assign this to me. I will work on this.

**Comment by Siddhant-K-code** [comment]
Sorry, @ShashwatNautiyal Just saw the message, and due to the limited access to Figma, I don't think it would be possible for you. You can take a look other issues (e.g. #3408), if you are interested
