### ISSUE TITLE
homepage sprint (part 5): content updates

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3382]
You can find the mockup [here](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=8898%3A17416&t=xSdAndqYzGskFOW4-1)

**Tasks**

- [x] update subheadline to "Ship software faster with secure cloud  development environments that just work."
- [x] change headline for trusted by section to "Speeding up +750k developers in teams like"
- [x] update success metrics (content + add a caption) 
<img width="608" alt="Bildschirm­foto 2023-02-06 um 13 36 44" src="https://user-images.githubusercontent.com/46345125/216973260-237adf58-cf4c-47ed-983d-96e1c25124f3.png">

- [x] add "what's a CDE?" section (overhauls the old "Your environment, your tools, your craft" section)
- [x] New IDE Component: all screenshots have been updated. You can find them [here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=2056%3A3271&t=y5hfRPbP2Ljoom8K-1) (Screenshots for Rider, Clion and Vim are still WIP)
- [x] New Toggle: default selection: Desktop & VS Code

- [x] update content and order of the feature section (see [here](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=8898%3A17416&t=xSdAndqYzGskFOW4-1))
- [x] add benefit overview 
<img width="626" alt="Bildschirm­foto 2023-02-06 um 13 43 23" src="https://user-images.githubusercontent.com/46345125/216974532-c86f318a-e1a1-4a81-a5b2-ddda0bd4d2db.png">

Let me know in case you need a mockup for dark theme or mobile @Siddhant-K-code 🙌

**Comment by Siddhant-K-code** [comment]
@chrifro Regarding IDE Components, Current design is overlapping the "Beta" labels:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/55068936/217156386-35fadcd3-c7e8-4d11-b154-a0897c797d9e.png">
