### ISSUE TITLE
Fully migrate the codebase to use Tailwind. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/website#648]
We should get rid of all the custom CSS to get rid of these kinds of performance issues https://github.com/gitpod-io/website/issues/643#issuecomment-863764621

- [x] avatars.scss => #1481
- [x] base.scss => #1488
- [x] blog_preview.scss => #1489
- [x] blog.scss => #1490
- [x] buttons.scss
- [x] cards.scss => #1500 
- [x] error_page.scss => #1486
- [x] feature_table.scss => #1516 
- [ ] forms.scss
- [x] images-across.css => #1487
- [x] layout_helpers.scss => https://github.com/gitpod-io/website/pull/1520
- [x] modal.scss https://github.com/gitpod-io/website/pull/1493
- [x] reset.scss => #1470 
- [x] screencasts.scss => #1491
- [x] team.scss => #1485
- [x] text_blobs.scss => #1492 
- [ ] typography.scss => Awaiting https://github.com/sveltejs/svelte/issues/2324
- [ ] variables.scss
- [x] blog.scss => #1491
- [x] markdown-common.scss => #1490
- [ ] styles.scss

`global.scss` is getting renamed to `gloabl.css` and used for the tailwind-layers

**Comment by mikenikles** [comment]
This is something we need to be very careful that it doesn't get out of control. We have quite a bit of custom CSS, removing pieces may impact parts of the website we not immediately consider.


The work for this issue has to happen in multiple, small PRs as much as this is possible. For example, the following are examples of individual PRs:
* Header
* Footer
* Docs left-side nav
* Docs & blog post content
* Titles across all pages
* Pricing cards
* Left / right content with images and text, such as used on the homepage and features pages

**Comment by nisarhassan12** [comment]
> Left / right content with images and text, such as used on the homepage and features pages

I have addressed this in https://github.com/gitpod-io/website/pull/719/commits/a4a3935ee584aae1d13aa9fba76ec3fea18144e4

**Comment by mikenikles** [comment]
We are going to keep this open for tracking purposes. We migrate individual components and pages to Tailwind when we touch them as part of other issues.

Over time, we will get to a point where we have minimal custom CSS. At that time, we will spend a day or two to migrate the remaining custom CSS and close this issue.

**Comment by JohannesLandgraf** [comment]
How is this progressing? We wanted to do this after we launched the website in March :)

**Comment by Cahllagerfeld** [comment]
I think the remaining ones are nice-to-have but not a blocker currently. I'd put it in the backlog for now, or even close the issue and open follow-up items for the remaining ones.

**Comment by chrifro** [comment]
Okay, your call if you want to close or keep the issue. Whatever works best for you :) 
I will remove it from the "needs technical help" column, as it's not prioritized

**Comment by chrifro** [comment]
I'd favor closing this issue as no progress has been documented here and opening a follow-up issue for remaining to-dos. What do you think @Siddhant-K-code ?
